
DOCKER_REGISTRY_URL="registry.ethz.ch"
DOCKER_REGISTRY_PROJECT_URL="$DOCKER_REGISTRY_URL/ics/l4acados"
docker login $DOCKER_REGISTRY_PROJECT_URL
for PYTHON_VERSION in 3.8 3.10 3.12; do
    docker build --build-arg PYTHON_VERSION=$PYTHON_VERSION -t "$DOCKER_REGISTRY_PROJECT_URL:$PYTHON_VERSION" .
    docker push "$DOCKER_REGISTRY_PROJECT_URL:$PYTHON_VERSION"
done
